### ISSUE TITLE
 Issue in WinML Demo

### ISSUE THREAD

**Issue by cheahengsoon** [microsoft/InsiderDevTourDemos19#8]
Hi Team,

I got an issue as a screenshot as below.
![WinMLissue](https://user-images.githubusercontent.com/2833325/58922529-dec2bc80-876d-11e9-9b85-5ad366d5995d.png)

**Comment by nitah-kelsy** [comment]
> Hi Team,
> I got an issue as a screenshot as below.

Hello. I can think of two things: (1) the path is long. In the demo scripts, I ask that you copy the project to your C: drive root. and (2) Did you reload the dependencies and the nuget packages?

**Comment by cheahengsoon** [comment]
@nitah-kelsy After I copy to the C: drive root. The problems solved. Thank you so much.
